### ISSUE TITLE
Support source generator debugging in the new Launch Profiles UI

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn-sdk#850]
In Dev17 we have a new UI for launch profiles, which replaces the legacy `ILaunchSettingsUIProvider` interface. Rather than having each provider specify it's own UI components, we now expect data about properties in order to present a unified experience.

The source generator debugger support in this repo should be extended to provide the relevant data for that experience, for launch profiles with command name `DebugRoslynComponent`.

Without support, editing of source generator debugging profiles is not available for C# projects in Dev17.

Docs exist to walk through this process here: https://github.com/dotnet/project-system/tree/main/docs/repo/property-pages

In particular the doc on [adding a new launch profile kind](https://github.com/dotnet/project-system/blob/main/docs/repo/property-pages/how-to-add-a-new-launch-profile-kind.md), and on [property specification](https://github.com/dotnet/project-system/blob/main/docs/repo/property-pages/property-specification.md).

Ping @drewnoakes or @tmeschter for help if anything is unclear.

**Comment by tmeschter** [comment]
Yeah, feel free to ping us for reviews or questions. Any issues you encounter are likely to affect others as well so we want to know about them.

**Comment by drewnoakes** [comment]
@jmarolf @chsienki a ping on this, as it will be a regression in 17.0 if omitted.

**Comment by drewnoakes** [comment]
Also reported in https://developercommunity.visualstudio.com/t/Debugging-Source-Generators-via-Debug-La/1511451.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn-sdk/pull/896

**Comment by ignatandrei** [comment]
Do we have a tutorial about this somewhere ?

**Comment by zhen8838** [comment]
@ignatandrei I record a video:

https://user-images.githubusercontent.com/26156999/153815974-65ce83d0-a3a2-4c07-8777-9d691d0243bd.mp4

**Comment by susch19** [comment]
If this option doesn't show up for you in VS2022, make sure you have the “.NET Compiler Platform SDK” Component installed. I somehow missed that and wondered why it didn't show up.

**Comment by TorreyGarland** [comment]
Can these new instructions be added to the "official" documentation for Source/Incremental Generators?

I tried following the video and it is still not working for me.

**Comment by susch19** [comment]
> Can these new instructions be added to the "official" documentation for Source/Incremental Generators?
> 
> I tried following the video and it is still not working for me.

Does the dropdown menu doesn't show the option?
Did you add `<IsRoslynComponent>true</IsRoslynComponent>` to the source code generator csproj PropertyGroup (Shown in the first few seconds of the video)?
Did you open the menu on the source code generator csproj?

If you can't select the target project, then check whether you have the source code generator referenced in the target project like so `<ProjectReference Include="..\YourSourceCodeGeneratorName\YourSourceCodeGeneratorName.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />`

That's all that should be needed, including the `.NET Compiler Platform SDK`, but I imagine you have this installed

If all that doesn't help, you can still create the launchSettings.json by yourself:
``` json
{
  "profiles": {
    "Your.SourceCode.Generator.Name": {
      "commandName": "DebugRoslynComponent",
      "targetProject": "..\\TargetProject\\TargetProject.csproj"
    }
  }
}
```

**Comment by TorreyGarland** [comment]
> > Can these new instructions be added to the "official" documentation for Source/Incremental Generators?
> > I tried following the video and it is still not working for me.
> 
> Does the dropdown menu doesn't show the option? Did you add `<IsRoslynComponent>true</IsRoslynComponent>` to the source code generator csproj PropertyGroup (Shown in the first few seconds of the video)? Did you open the menu on the source code generator csproj?
> 
> If you can't select the target project, then check whether you have the source code generator referenced in the target project like so `<ProjectReference Include="..\YourSourceCodeGeneratorName\YourSourceCodeGeneratorName.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />`
> 
> That's all that should be needed, including the `.NET Compiler Platform SDK`, but I imagine you have this installed
> 
> If all that doesn't help, you can still create the launchSettings.json by yourself:
> 
> ```json
> {
>   "profiles": {
>     "Your.SourceCode.Generator.Name": {
>       "commandName": "DebugRoslynComponent",
>       "targetProject": "..\\TargetProject\\TargetProject.csproj"
>     }
>   }
> }
> ```
![launch-profiles](https://user-images.githubusercontent.com/1054548/154857462-667a6a0c-7269-42c5-9914-0c4f729be8c7.png)

![launch-settings-2](https://user-images.githubusercontent.com/1054548/154857481-5d2b6d63-7f08-41e6-a4b0-95b5cd70198f.png)

![solution-explorer](https://user-images.githubusercontent.com/1054548/154857486-f59eb682-04af-4596-81f0-bfb4296e0a6e.png)

![error-message](https://user-images.githubusercontent.com/1054548/154857504-201d0488-4dd0-449b-bd68-268d65ad9ebe.png)

**Comment by susch19** [comment]
@TorreyGarland 
This problem is known and tracked here:
https://github.com/dotnet/roslyn/issues/55802

So one or multiple of your dependencies is the problem, so either remove one after another, until it works, create a new generator and add them until it doesn't work or wait for a fix.

**Comment by TorreyGarland** [comment]
strange... works now perfectly with all previous dependencies on both SourceGenerators and IncrementalGenerators.

I didn't update the sdk.

Maybe good old fashioned restart computer worked.

**Comment by TorreyGarland** [comment]
> 

I spoke too soon... it works perfectly for a console app.  

it failed with the "filename or extension is too long" message for a Blazor Server App project.

**Comment by drewnoakes** [comment]
That's the same error message discussed in https://github.com/dotnet/roslyn/issues/55802.

**Comment by TorreyGarland** [comment]
> That's the same error message discussed in [dotnet/roslyn#55802](https://github.com/dotnet/roslyn/issues/55802).

I'm sorry, I didn't see anything specific to blazor apps in that discussion.

**Comment by JoanComasFdz** [comment]
This has worked for me. I have tried to streamline the instructions here:

https://github.com/JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022

**Comment by TorreyGarland** [comment]
> This has worked for me. I have tried to streamline the instructions here:
> 
> https://github.com/JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022

try it with blank blazor server app.  does it work for you?

**Comment by JoanComasFdz** [comment]
> > This has worked for me. I have tried to streamline the instructions here:
> > https://github.com/JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022
> 
> try it with blank blazor server app. does it work for you?

I just followed my own instructions and yes it works: https://github.com/JoanComasFdz/BlazorApp1

**Comment by TorreyGarland** [comment]
> > > This has worked for me. I have tried to streamline the instructions here:
> > > https://github.com/JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022
> > 
> > 
> > try it with blank blazor server app. does it work for you?
> 
> I just followed my own instructions and yes it works: https://github.com/JoanComasFdz/BlazorApp1
> 
> Make sure tu put the breakpoints in the SourceGenerator Initialize and Execute methods to see it working.
> 
> Also for reference: I am using VS 2022 17.1.0

thank you for looking into to this

**Comment by ignatandrei** [comment]
Still does not work for me.  I am using VS2022 vs 17.1.1 
The  "Roslyn" menu does not appear , even if I have downloaded https://github.com/JoanComasFdz/BlazorApp1

Any idea why?

**Comment by ignatandrei** [comment]
> .NET Compiler Platform SDK

Solved with https://github.com/dotnet/roslyn-sdk/issues/850#issuecomment-1041839050 . THanks. !

**Comment by TorreyGarland** [comment]
> > .NET Compiler Platform SDK
> 
> Solved with [#850 (comment)](https://github.com/dotnet/roslyn-sdk/issues/850#issuecomment-1041839050) . THanks. !

this worked with a Blazor Server app?  I have the most recent SDK and it still failed.

**Comment by HClausing** [comment]
I've tried this way for debugging, but got this on terminal, related to target project:

![image](https://user-images.githubusercontent.com/15158923/163218628-02a2402d-8eba-4cca-9a5a-0071e0baaf04.png)

But the target project compiles well on Visual Studio, and I can debug it without throubles.

The files listed on Errors CS2001 really don't exist. I really don't know why it's happening.

**Comment by HClausing** [comment]
I've figured that it maybe related to spaces on project folder's name. After renaming "DataGrid Columns" to "DataGridColumns" the number of errors reduced:

![image](https://user-images.githubusercontent.com/15158923/163222555-32e47f4e-6131-4c0e-9546-93262a1bbe12.png)
